services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex123
      POSTGRES_DB: drizzle-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
